### ISSUE TITLE
synonymous_calculation/bin/pal2nal.pl has no license, not distributable

### ISSUE THREAD

**Issue by mr-c** [tanghaibao/bio-pipeline#1]
Hello @tanghaibao 

I found your repository because I'm trying to find a version of pal2nal that is licensed by the authors for redistribution.

https://github.com/fstrozzi/scalability-reproducibility-chapter/issues/1

Alas you seem to be using the same version we're looking at, and the lack of license means that you can't even put a copy on GitHub.

If you happen to know the authors in any way, you could help us to petition them to add a license: https://lists.debian.org/debian-med/2017/10/msg00019.html

In the mean time I recommend that you remove this copy of pal2nal from GitHub as no one besides the authors have the legal right to distribute the code.

Sorry to be the bearer of bad news,

**Comment by tanghaibao** [comment]
@mr-c 
Thanks Michael - I used pal2nal.pl over 10 years ago, and I have overlooked its license requirement. 

Haibao
