### ISSUE TITLE
Nim wrapper to kseq

### ISSUE THREAD

**Issue by andreas-wilm** [tanghaibao/bio-pipeline#2]
Dear Haibao,

I came across this repo after a failed attempt to write a Nim wrapper for Heng Li's kseq. Awesome stuff! Native versions are all very slow, possibly due to reasons discussed in [this post]( https://github.com/nim-lang/Nim/issues/3084) on the Nim forum. My plan was to modify your code and make it ready for Nimble submission, however I can't get it compiled because .`./kseq.h` is missing (running `nimble test` in `klib/nim`). You have a few versions of that file in the repo but I couldn't get either to work . Maybe that file is simply missing?

Could you help?

Many thanks!
Andreas

**Comment by tanghaibao** [comment]
@andreas-wilm 

I just updated `htlib.nim`. The path was incorrect and should point to `kseq.h` in the same directory. Let me know if you can get things to compile now (it works on my mac with nim version `1.0.2`).

**Comment by andreas-wilm** [comment]
Thanks a lot! This works. Sorry I thought I commented here already


Andreas
