### ISSUE TITLE
Move kseq nim out to make nimble package

### ISSUE THREAD

**Issue by andreas-wilm** [tanghaibao/bio-pipeline#4]
Dear Haibao,

Would you be open to moving the kseq nim bits into its own repo and publish as a nimble package? This could either be a new repo (ideally having kseq in its name to make the roots clear) or simply using https://github.com/sdwfrost/nimkseq which is empty right now :) If you don't have the time I'm happy to help. I noticed you have no license added to your repo so guess I better ask.

PS:  Sorry I thought could swear I asked you already, but I can't find any reference to it

**Comment by tanghaibao** [comment]
@andreas-wilm 

Please go ahead and add those bits into the repo that you have `sdwfrost/nimkseq`- you probably have noticed that there is actually not a lot in my kseq nim bits - and feel free to start a new nimble package.

Haibao

**Comment by andreas-wilm** [comment]
Thanks a lot Haibao!

**Comment by andreas-wilm** [comment]
For the sake of completeness: https://github.com/andreas-wilm/nimreadfq

Thanks again!
