### ISSUE TITLE
License for poaV2? 

### ISSUE THREAD

**Issue by NatPRoach** [tanghaibao/bio-pipeline#5]
Hello,
I'm working on a tool that uses poaV2 to do partial order alignment. I've managed to bind your poaV2 library in nim, but just noticed that there is no stated license for poaV2 or the bio-pipeline repo in general. I wanted to check with you whether it is acceptable for me to bind your library and distribute the code from the poaV2 software in a nim software package.
I'd obviously credit you and this repo as the source of the library, and link to this repo in my README and any publication resulting from the completion of the tool.
Thanks for your time and the great software! Please let me know either way when you get the chance.

**Comment by tanghaibao** [comment]
@NatPRoach 

I must point out that the original credit of POA should go to Christopher Lee:
https://academic.oup.com/bioinformatics/article/18/3/452/236691
I downloaded the original code from http://www.bioinformatics.ucla.edu/poa (which is now a 404).

I did not recall seeing a license when I first downloaded the poa code. I remember to have attempted to track down the original license but forgot what my finding was. I had assumed it was ok. For my project, I then made a couple of modifications to this software.

I have no problem granting you the license to use my modifications but I'll at least try to locate the license for the original code. I'll post here if I get an answer.

Haibao

**Comment by tanghaibao** [comment]
@NatPRoach 

Did some googling and found it here:
http://manpages.ubuntu.com/manpages/xenial/man1/poa.1.html

```
Copyright (C) 2001, 2006 Christopher Lee <leec@mbi.ucla.edu>. POA is free software. You
can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation.

This manual page was written by Charles Plessy <charles-debian-nospam@plessy.org> for the
Debian(TM) system (but may be used by others). Permission is granted to copy, distribute
and/or modify this document under the terms of the GNU General Public License, Version 2
any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common-licenses/GPL.
```
So that's clear. I'll create a LICENSE and share it with you.

**Comment by NatPRoach** [comment]
Thanks Haibao! I appreciate it.

**Comment by tanghaibao** [comment]
@NatPRoach 

The license is ready: https://github.com/tanghaibao/bio-pipeline/blob/master/poaV2/LICENSE

Note that I had to use GPL v2 due to the nature of the original license being GPL v2.
